### ISSUE TITLE
Tool to download covers

### ISSUE THREAD

**Issue by ThePromidius** [ThePromidius/Manga-Manager#71]
The idea behind this fr is to be able to download covers from mangadex api or any other providing the url or id of the manga. Ideally a folder will be generated with the downloaded covers in it
# To-Do list
- [x] Create a folder per serie
- [x] prompt to put in manga id / url 
- [x] check if that volume or other image that contains same volume number exists ans download or exclude accordingly
